'use strict';
const c=document.querySelector('canvas'),g=c.getContext('2d'),status=document.querySelector('#status'),actions=document.querySelector('#actions');
const species=[{name:'Cindercub',color:'#ff925c',type:'Fire'},{name:'Mossfin',color:'#69dda0',type:'Leaf'},{name:'Rainwing',color:'#77cfff',type:'Water'}];
let s={x:4,y:5,hp:40,max:40,level:1,wins:0,balls:8,team:[0],active:0,won:false},battle=null,turn=false,message='Welcome to Fernbrook! Your Cindercub is ready.',last=0;
try{const saved=JSON.parse(localStorage.getItem('ember-leaf-v1'));if(saved&&Array.isArray(saved.team)&&saved.team.length&&Number.isFinite(saved.hp))s=saved;}catch{}
function save(){try{localStorage.setItem('ember-leaf-v1',JSON.stringify(s));}catch{}}
function tile(x,y){if(x<1||x>28||y<1||y>16)return 1;if(x>=11&&x<=13&&y!==8)return 2;if((x>5&&x<10&&y>4&&y<14)||(x>17&&y>8&&y<16))return 3;return 0;}
function say(t){message=t;draw();}
function creature(id,x,y,scale=1){const q=species[id];g.save();g.translate(x,y);g.scale(scale,scale);g.fillStyle='#15263844';g.beginPath();g.ellipse(0,20,28,9,0,0,7);g.fill();g.fillStyle=q.color;g.fillRect(-20,-20,40,38);g.fillRect(-26,-30,12,24);g.fillRect(14,-30,12,24);g.fillRect(-18,17,12,8);g.fillRect(7,17,12,8);g.fillStyle='#112333';g.fillRect(-11,-10,6,7);g.fillRect(8,-10,6,7);g.fillRect(-4,6,10,3);if(id===1){g.fillStyle='#24814e';g.fillRect(-5,-35,11,19);}if(id===2){g.fillStyle='#c3ebff';g.fillRect(-37,-6,17,11);g.fillRect(20,-6,17,11);}g.restore();}
function label(t,x,y,col='#eef5e3',size=16){g.fillStyle=col;g.font=`bold ${size}px monospace`;g.fillText(t,x,y);}
function draw(){g.clearRect(0,0,960,576);if(!battle){for(let y=0;y<18;y++)for(let x=0;x<30;x++){let t=tile(x,y);g.fillStyle=['#9ecb79','#315f4a','#4b9eae','#70aa61'][t];g.fillRect(x*32,y*32,32,32);if(t===3){g.fillStyle='#42864c';g.fillRect(x*32+6,y*32+13,3,12);g.fillRect(x*32+20,y*32+6,3,17);}if(t===1){g.fillStyle='#407858';g.fillRect(x*32+4,y*32+3,24,20);}}g.fillStyle='#dcca91';g.fillRect(32,8*32,896,32);g.fillStyle='#e2e9cd';g.fillRect(64,64,96,64);g.fillStyle='#ba5960';g.fillRect(58,55,108,20);label('+',101,101,'#ba5960',27);g.fillStyle='#847198';g.fillRect(25*32,3*32,64,64);label('♜',25*32+17,3*32+40,'#fff',30);g.fillStyle='#e75f58';g.fillRect(s.x*32+7,s.y*32+2,18,10);g.fillStyle='#ffdfb1';g.fillRect(s.x*32+9,s.y*32+12,14,10);g.fillStyle='#2e4773';g.fillRect(s.x*32+6,s.y*32+22,20,10);label('FERNBROOK',185,92,'#244e40');label('GUARDIAN',767,85,'#244e40');}else{g.fillStyle='#c6d9ad';g.fillRect(0,0,960,576);g.fillStyle='#a3be90';g.beginPath();g.ellipse(695,220,160,45,0,0,7);g.ellipse(255,440,175,40,0,0,7);g.fill();creature(battle.id,695,170,battle.boss?3.5:2.6);creature(s.active,255,375,3);label(`${battle.boss?'GUARDIAN · ':''}${species[battle.id].name}`,490,65,'#294332',25);label(`HP ${battle.hp} / ${battle.max}`,490,97,'#294332');g.fillStyle='#345a42';g.fillRect(490,110,330,12);g.fillStyle='#81d985';g.fillRect(490,110,330*battle.hp/battle.max,12);label(`${species[s.active].name} · LV ${s.level}`,540,380,'#294332',24);label(`HP ${s.hp} / ${s.max}`,540,415,'#294332');}g.fillStyle='#102820e8';g.fillRect(0,532,960,44);label(`Lv ${s.level}   HP ${s.hp}/${s.max}   Capsules ${s.balls}   Wins ${s.wins}   Collection ${s.team.length}/3${s.won?'   ★ GUARDIAN DEFEATED':''}`,18,559);status.textContent=message;actions.replaceChildren();if(battle){[['Strike',()=>attack(false)],['Element burst',()=>attack(true)],['Throw capsule',capture],['Run',()=>{if(battle.boss){say('The guardian blocks your escape!');return;}battle=null;say('You escaped safely.');}]].forEach(([t,f])=>button(t,f,turn));}else{button('Meet a wild creature',()=>{if(tile(s.x,s.y)===3)encounter();else say('Walk into tall grass first.');});}s.team.forEach(id=>button(`${s.active===id?'● ':''}${species[id].name}`,()=>{s.active=id;save();if(battle)retaliate('Companion switched.');else draw();},turn||s.active===id));}
function button(t,f,disabled=false){let b=document.createElement('button');b.textContent=t;b.onclick=f;b.disabled=disabled;actions.append(b);}
function encounter(boss=false){const id=boss?2:Math.floor(Math.random()*3),hp=boss?75:20+s.level*3;battle={id,hp,max:hp,boss,burst:false};say(`${boss?'The grove guardian challenges you!':'A wild '+species[id].name+' appeared!'}`);}
function finish(text){s.wins++;s.level=1+Math.floor(s.wins/2);s.max=40+(s.level-1)*8;s.hp=Math.min(s.max,s.hp+12);if(battle.boss)s.won=true;battle=null;save();say(text+' You recovered 12 HP.');}
function retaliate(text){s.hp=Math.max(0,s.hp-(battle.boss?9:4+Math.floor(Math.random()*4)));if(s.hp<=0){battle=null;s.x=4;s.y=5;s.hp=s.max;s.balls=Math.max(8,s.balls);text='Your companion fainted. The clinic restored your team.';}save();say(text);}
function attack(special){if(!battle)return;if(special&&battle.burst){say('One element burst per battle. Use Strike!');return;}let damage=7+s.level*2;if(special){battle.burst=true;damage+=8;if((s.active+1)%3===battle.id)damage+=6;}battle.hp=Math.max(0,battle.hp-damage);if(!battle.hp)finish(battle.boss?'You earned the Grove Badge! Adventure complete.':'Battle won!');else retaliate(`You dealt ${damage} damage. The opponent struck back.`);}
function capture(){if(battle.boss){say('The guardian cannot be captured. Defeat it to earn the badge.');return;}if(!s.balls){say('No capsules left. Visit the clinic.');return;}s.balls--;if(Math.random()<.25+.65*(1-battle.hp/battle.max)){if(!s.team.includes(battle.id))s.team.push(battle.id);finish(`${species[battle.id].name} caught!`);}else retaliate('The creature escaped your capsule and attacked!');}
function move(dx,dy){if(battle)return;const x=s.x+dx,y=s.y+dy;if([1,2].includes(tile(x,y)))return;s.x=x;s.y=y;save();if(tile(x,y)===3&&Math.random()<.14)encounter();else draw();}
function interact(){if(battle)return;if(Math.hypot(s.x-3,s.y-3)<3){s.hp=s.max;s.balls=Math.max(8,s.balls);save();say('Clinic: team healed and capsules refilled!');}else if(Math.hypot(s.x-26,s.y-4)<3){if(s.wins<3)say('Guardian: win three wild battles before challenging me.');else if(s.won)say('You are the Grove Champion! Keep exploring and collecting.');else encounter(true);}else say('Explore the tall grass, visit the clinic, or find the eastern shrine.');}
document.addEventListener('keydown',e=>{const m={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]}[e.key];if(m){e.preventDefault();if(Date.now()-last>110){move(...m);last=Date.now();}}if(e.key.toLowerCase()==='e')interact();});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>move(...b.dataset.move.split(',').map(Number)));document.querySelector('#interact').onclick=interact;document.querySelector('#reset').onclick=()=>{if(confirm('Start a new adventure? This replaces your saved progress.')){try{localStorage.removeItem('ember-leaf-v1');}catch{}location.reload();}};draw();
