'use strict';
// District expansion: persistent implants, 3-axis camera, avatar meshes and missions.
gear.cloneeye={name:'CLONE EYE',desc:'C: summon two armed holographic copies for 18 seconds. Red ocular implant.'};
gear.spring={name:'VECTOR TENDONS',desc:'Leg implants: higher jumps and faster air movement.'};
gear.repair={name:'REPAIR HEART',desc:'Regenerates integrity while you are out of combat.'};
gear.sanvesyn.desc='Q: 5 seconds of frozen world time and 85% faster movement. Spinal implant.';
const slots={sanvesyn:'spine',cloneeye:'eye',prism:'eye',plating:'torso',repair:'torso',overdrive:'legs',spring:'legs'};
profile.credits=Math.max(0,Number(profile.credits)||0);
profile.mods={power:0,magazine:0,cooling:0,...profile.mods};
for(const k of Object.keys(profile.mods))profile.mods[k]=Math.min(3,Math.max(0,Math.floor(Number(profile.mods[k])||0)));
profile.slots=profile.slots&&typeof profile.slots==='object'?profile.slots:{};
if(profile.equipped&&slots[profile.equipped]&&!profile.slots[slots[profile.equipped]])profile.slots[slots[profile.equipped]]=profile.equipped;
for(const [slot,id] of Object.entries(profile.slots))if(!profile.owned.includes(id)||slots[id]!==slot)delete profile.slots[slot];
// Existing players get the new ability as a one-time expansion reward.
if(!profile.cloneGift){if(!profile.owned.includes('cloneeye'))profile.owned.push('cloneeye');profile.slots.eye='cloneeye';profile.cloneGift=true;}
const has=id=>profile.slots[slots[id]]===id;
const hpLimit=()=>has('plating')?140:100;
const magSize=()=>12+profile.mods.magazine*4+(has('overdrive')?6:0);
let mode='campaign',paused=false,clones=[],cloneCD=0,combatAge=0,mission=null,completed=0,ambientTimer=15,avatarYaw=.6,aiming=false;
const districts=['111111111111111111111111','100000000000000000000001','100000000000000000000001','100000011100001110000001','100000010100001010000001','100000010000001000000001','100000011100001110000001','100000000000000000000001','100000000000000000000001','101110000000000001110001','101010000111000001010001','100010000101000000010001','101110000000000001110001','100000000111000000000001','100000000000000000000001','100000000000000000000001','100000000000000000000001','111111111111111111111111'];
const sites=[{name:'SAFEHOUSE',x:3.5,y:3.5,color:'#6cffe0',kind:'home'},{name:'AURORA VAULT',x:8.5,y:4.5,color:'#ffc979',kind:'heist'},{name:'DATA EXCHANGE',x:15.5,y:4.5,color:'#df91ff',kind:'data'},{name:'DRONE DEPOT',x:10.5,y:11.5,color:'#ff7eaa',kind:'bounty'}];
const menuPanel=document.querySelector('#operator-menu'),avatarCanvas=document.querySelector('#avatar'),ag=avatarCanvas.getContext('2d');
function persist(){save();}
function refresh(){document.querySelector('#progress').textContent=`OPERATOR LV ${level()} / ${profile.xp%100} XP / ${profile.credits} CREDITS / CACHES ${profile.boxes}`;document.querySelector('#loot').disabled=profile.boxes<1||(running&&!paused);document.querySelector('#loot').textContent=`Open cache (${profile.boxes})`;const inventory=document.querySelector('#inventory');inventory.replaceChildren();for(const id of profile.owned){const b=document.createElement('button');b.textContent=`${has(id)?'INSTALLED / ':''}${gear[id].name}`;b.title=gear[id].desc;b.disabled=running&&!paused;b.onclick=()=>{if(running&&!paused)return;profile.slots[slots[id]]=id;profile.equipped=id;if(p)p.hp=Math.min(p.hp,hpLimit());ammo=Math.min(ammo,magSize());persist();note=gear[id].desc;refresh();};inventory.append(b);}document.querySelector('#gear-info').textContent='Four slots: spine, eye, torso and legs. Sanvesyn and Clone Eye can be installed together.';document.querySelector('#implant-list').textContent=Object.entries(profile.slots).map(([slot,id])=>`${slot.toUpperCase()}: ${gear[id].name}`).join(' | ')||'No implants installed';document.querySelector('#wallet').textContent=`${profile.credits} CREDITS / LV ${level()}`;const mods=document.querySelector('#weapon-mods');mods.replaceChildren();for(const [id,label] of [['power','Amplifier / +1 damage'],['magazine','Cell bank / +4 ammo'],['cooling','Cooling / faster fire']]){const b=document.createElement('button'),rank=profile.mods[id],cost=80*(rank+1);b.textContent=`${label} / ${rank}/3 / ${rank===3?'MAX':cost+' credits'}`;b.disabled=rank===3||profile.credits<cost;b.onclick=()=>{if(running&&!paused)return;if(profile.mods[id]>=3||profile.credits<cost)return;profile.credits-=cost;profile.mods[id]++;persist();refresh();};mods.append(b);}document.querySelector('#mission-list').innerHTML=sites.filter(s=>s.kind!=='home').map(s=>`<p><b>${s.name}</b><br>${s.kind==='heist'?'Take a corporate credit core and extract.':s.kind==='data'?'Download the archive and extract.':'Disable four rogue drones and extract.'} <span>180 credits + 1 cache</span></p>`).join('');}
ui=refresh;
openLoot=function(){if(profile.boxes<1||(running&&!paused))return;profile.boxes--;const missing=Object.keys(gear).filter(id=>!profile.owned.includes(id));const id=!profile.owned.includes('sanvesyn')?'sanvesyn':missing.length?missing[Math.floor(Math.random()*missing.length)]:Object.keys(gear)[Math.floor(Math.random()*Object.keys(gear).length)];if(profile.owned.includes(id)){profile.xp+=40;profile.credits+=30;note=`Duplicate ${gear[id].name}: +40 XP, +30 credits.`;}else{profile.owned.push(id);profile.slots[slots[id]]=id;note=`UNLOCKED / ${gear[id].name}`;}profile.opened++;persist();refresh();document.querySelector('#reward').textContent=note;};
function toggleMenu(force){paused=typeof force==='boolean'?force:!paused;menuPanel.hidden=!paused;keys={};aiming=false;if(paused){document.exitPointerLock?.();refresh();document.querySelector('#close-menu').focus();}else canvas.focus();}
const baseStart=start;
start=function(){mode='campaign';toggleMenu(false);baseStart();p.z=0;p.vz=0;p.pitch=0;p.hp=hpLimit();ammo=magSize();clones=[];cloneCD=0;mission=null;combatAge=0;};
function freeplay(){start();mode='freeplay';map=districts;bots=[];sector=1;wave=1;completed=0;ambientTimer=10;p.x=3.5;p.y=3.5;note='FREEPLAY / Explore the district. Visit a marked site and press E.';refresh();}
function jump(){if(running&&!paused&&p.z<=.001){p.vz=has('spring')?4.4:3.25;}}
activate=function(){if(!running||paused)return;if(!has('sanvesyn')){note='Install Sanvesyn in your spine slot in the operator menu.';return;}if(freezeCD>0){note=`Sanvesyn recharge: ${Math.ceil(freezeCD)}s`;return;}freeze=5;freezeCD=23;note='SANVESYN / TIME LOCK / SPEED +85%';};
function summon(){if(!running||paused)return;if(!has('cloneeye')){note='Install Clone Eye in the eye slot.';return;}if(cloneCD>0){note=`Clone Eye recharge: ${Math.ceil(cloneCD)}s`;return;}clones=[];for(const side of [-1,1]){let x=p.x+Math.sin(p.a)*side*.65,y=p.y-Math.cos(p.a)*side*.65;if(!clear(x,y)){x=p.x;y=p.y;}clones.push({x,y,a:p.a,z:0,life:18,cd:.2,hp:60,max:60});}cloneCD=26;note='CLONE EYE / TWO COMBAT COPIES ONLINE';}
reload=function(){if(running&&!paused&&!reloadTime&&ammo<magSize())reloadTime=.95;};
function killBot(b){bots=bots.filter(x=>x!==b);kills++;profile.xp+=20;profile.credits+=12;if(mission&&mission.phase==='fight')mission.count++;persist();refresh();}
shoot=function(){if(!running||paused||reloadTime||shotCD>0)return;if(ammo<=0){reload();return;}ammo--;shotCD=Math.max(.09,.22-profile.mods.cooling*.035);const eye=.55+p.z,slope=Math.tan(p.pitch),distance=trace(p.x,p.y,p.a,35);let nearest=distance,hit=null;if(slope<0)nearest=Math.min(nearest,eye/-slope);for(const b of bots){const dx=b.x-p.x,dy=b.y-p.y,along=dx*Math.cos(p.a)+dy*Math.sin(p.a),side=Math.abs(-dx*Math.sin(p.a)+dy*Math.cos(p.a)),height=eye+slope*along;if(along>0&&along<nearest&&side<.4&&height>.28&&height<.99){nearest=along;hit=b;}}const end={x:p.x+Math.cos(p.a)*nearest,y:p.y+Math.sin(p.a)*nearest,z:eye+slope*nearest};beams.push({from:{x:p.x+Math.sin(p.a)*.12+Math.cos(p.a)*.4,y:p.y-Math.cos(p.a)*.12+Math.sin(p.a)*.4,z:eye-.15},to:end,life:.18,player:true,color:has('prism')?'#ee9aff':'#6bffff'});for(let i=0;i<8;i++)sparks.push({...end,vx:(Math.random()-.5)*1.5,vy:(Math.random()-.5)*1.5,vz:Math.random()*1.5,life:.3});if(hit){hit.hp-=1+profile.mods.power+(has('prism')?1:0);note='TARGET HIT';if(hit.hp<=0)killBot(hit);}};
function spawnGuards(count,site){const candidates=[];for(let y=1;y<map.length-1;y++)for(let x=1;x<map[0].length-1;x++)if(clear(x+.5,y+.5)&&Math.hypot(x+.5-p.x,y+.5-p.y)>2&&(!site||Math.hypot(x+.5-site.x,y+.5-site.y)<7))candidates.push({x:x+.5,y:y+.5});for(let i=0;i<count&&candidates.length;i++){const pos=candidates.splice(Math.floor(Math.random()*candidates.length),1)[0];bots.push({...pos,hp:3+Math.floor(completed/2),max:3+Math.floor(completed/2),cd:1+i*.25,phase:i,type:i%3});}}
function interact(){if(!running||paused||mode!=='freeplay')return;const site=sites.find(s=>Math.hypot(s.x-p.x,s.y-p.y)<1.5);if(!site){note='Move close to a marked terminal to interact.';return;}if(site.kind==='home'){if(mission?.phase==='extract'){profile.credits+=180;profile.xp+=100;profile.boxes++;completed++;mission=null;bots=[];note='CONTRACT COMPLETE / +180 CREDITS / +100 XP / +1 CACHE';persist();}else note='SAFEHOUSE / Integrity restored, ammo refilled. M opens implants.';p.hp=hpLimit();ammo=magSize();refresh();return;}if(mission){note='Finish the active contract and return to the safehouse.';return;}mission={site,phase:site.kind==='bounty'?'fight':'hack',count:0,progress:0};spawnGuards(4,site);note=site.kind==='bounty'?'CONTRACT / Eliminate four drones, then extract.':'CONTRACT / Stay near the terminal for 5 seconds, then escape to the safehouse.';}
update=function(dt){if(paused)return;const frozen=freeze>0;shotCD=Math.max(0,shotCD-dt);hurt=Math.max(0,hurt-dt);freezeCD=Math.max(0,freezeCD-dt);cloneCD=Math.max(0,cloneCD-dt);freeze=Math.max(0,freeze-dt);combatAge+=dt;if(!frozen)worldTime+=dt;if(reloadTime){reloadTime=Math.max(0,reloadTime-dt);if(!reloadTime)ammo=magSize();}p.a+=((keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0))*dt*2.1;p.pitch=Math.max(-.65,Math.min(.65,p.pitch+((keys.ArrowUp?1:0)-(keys.ArrowDown?1:0))*dt));p.vz-=dt*8;p.z=Math.max(0,p.z+p.vz*dt);if(p.z===0)p.vz=0;const forward=(keys.KeyW?1:0)-(keys.KeyS?1:0),side=(keys.KeyD?1:0)-(keys.KeyA?1:0),speed=(has('overdrive')?3.65:2.8)*(frozen?1.85:1)*(keys.ShiftLeft?1.35:1)*dt/Math.max(1,Math.hypot(forward,side));move(p,(Math.cos(p.a)*forward-Math.sin(p.a)*side)*speed,(Math.sin(p.a)*forward+Math.cos(p.a)*side)*speed);if(aiming||keys.KeyF)shoot();if(has('repair')&&combatAge>5)p.hp=Math.min(hpLimit(),p.hp+dt*4);
if(!frozen){for(const b of bots){let targets=[p,...clones],target=targets.sort((a,c)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(c.x-b.x,c.y-b.y))[0],d=Math.hypot(target.x-b.x,target.y-b.y),a=Math.atan2(target.y-b.y,target.x-b.x);b.cd-=dt;if(d>2)move(b,Math.cos(a)*dt*.65,Math.sin(a)*dt*.65);if(d<10&&b.cd<=0&&trace(b.x,b.y,a,d)>=d){beams.push({player:false,x:b.x,y:b.y,z:.6,a,vz:((target.z||0)+.55-.6)/Math.max(.2,d)*5,remaining:d+.7,life:3,color:'#ff598d'});b.cd=2.1;}}for(const cl of clones){cl.life-=dt;cl.cd-=dt;const target=[...bots].sort((a,b)=>Math.hypot(a.x-cl.x,a.y-cl.y)-Math.hypot(b.x-cl.x,b.y-cl.y))[0];if(target){let d=Math.hypot(target.x-cl.x,target.y-cl.y),a=Math.atan2(target.y-cl.y,target.x-cl.x);cl.a=a;if(d>3)move(cl,Math.cos(a)*dt*2,Math.sin(a)*dt*2);if(d<9&&cl.cd<=0&&trace(cl.x,cl.y,a,d)>=d){beams.push({player:false,ally:true,from:{x:cl.x,y:cl.y,z:.65},to:{x:target.x,y:target.y,z:.6},life:.18,color:'#a2b5ff'});target.hp--;cl.cd=.75;if(target.hp<=0)killBot(target);}}else{const d=Math.hypot(cl.x-p.x,cl.y-p.y);if(d>2)move(cl,(p.x-cl.x)/d*dt*2,(p.y-cl.y)/d*dt*2);}}clones=clones.filter(cl=>cl.life>0&&cl.hp>0);}
for(const b of beams){if(frozen&&!b.player)continue;b.life-=dt;if(!b.player&&!b.ally){b.x+=Math.cos(b.a)*dt*5;b.y+=Math.sin(b.a)*dt*5;b.z+=b.vz*dt;b.remaining-=dt*5;if(wall(b.x,b.y)||b.z<0||b.remaining<0)b.life=0;for(const target of [p,...clones])if(b.life>0&&Math.hypot(b.x-target.x,b.y-target.y)<.3&&Math.abs(b.z-((target.z||0)+.5))<.45){target.hp=Math.max(0,target.hp-(target===p&&has('plating')?6:10));b.life=0;if(target===p){hurt=.25;combatAge=0;}}}}beams=beams.filter(b=>b.life>0);for(const s of sparks){s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.z+=s.vz*dt;s.vz-=dt*3;}sparks=sparks.filter(s=>s.life>0);
if(mode==='freeplay'&&!frozen){ambientTimer-=dt;if(ambientTimer<=0){if(bots.length<5&&!mission)spawnGuards(2);ambientTimer=20;}if(mission?.phase==='hack'&&Math.hypot(p.x-mission.site.x,p.y-mission.site.y)<1.7){mission.progress+=dt;if(mission.progress>=5){mission.phase='extract';note='PACKAGE SECURED / Return to the green safehouse.';}}if(mission?.phase==='fight'&&mission.count>=4){mission.phase='extract';note='BOUNTY COMPLETE / Return to the safehouse.';}}
if(p.hp<=0){running=false;freeze=0;note='SIGNAL LOST / Redeploy to try again.';mission=null;clones=[];between=false;document.exitPointerLock?.();refresh();}else if(mode==='campaign'&&!bots.length&&!frozen){if(wave===3){profile.credits+=100;finish(`SECTOR ${sector} SECURED`,true);refresh();}else{wave++;p.hp=Math.min(hpLimit(),p.hp+20);ammo=magSize();spawn();}}};
project=function(v){const dx=v.x-p.x,dy=v.y-p.y,d=dx*Math.cos(p.a)+dy*Math.sin(p.a),side=-dx*Math.sin(p.a)+dy*Math.cos(p.a),up=v.z-(.55+(p.z||0)),cp=Math.cos(p.pitch||0),sp=Math.sin(p.pitch||0),z=d*cp+up*sp;return z>.06?{x:480+side*738/z,y:288-(up*cp-d*sp)*738/z,d}:null;};
// One articulated mesh is used for the rotating operator preview and combat copies.
function avatarMesh(x,y,z,yaw,paint,projector,context,clip=false){const faces=[];function box(cx,cy,cz,sx,sy,sz,colors){const vertices=[];for(const zz of [-1,1])for(const yy of [-1,1])for(const xx of [-1,1]){let lx=cx+xx*sx/2,ly=cy+yy*sy/2;vertices.push(projector({x:x+lx*Math.cos(yaw)-ly*Math.sin(yaw),y:y+lx*Math.sin(yaw)+ly*Math.cos(yaw),z:z+cz+zz*sz/2}));}for(const [indices,i] of [[[0,1,3,2],2],[[4,6,7,5],0],[[0,4,5,1],1],[[2,3,7,6],2],[[0,2,6,4],1],[[1,5,7,3],2]]){const pts=indices.map(k=>vertices[k]);if(pts.every(Boolean))faces.push({pts,color:colors[i],d:pts.reduce((n,v)=>n+v.d,0)/4});}}
const armor=paint?['#96bfff','#536cce','#36407d']:['#85c9dd','#326482','#193750'],dark=['#526981','#26364c','#162437'],glow=['#a3ffe9','#38c9bd','#278d9e'];box(0,0,.69,.38,.22,.4,armor);box(0,0,.97,.23,.22,.23,dark);box(0,-.12,.99,.2,.025,.075,glow);if(has('cloneeye'))box(.064,-.14,.99,.065,.025,.055,['#ff8187','#ff244f','#b21851']);for(const side of [-1,1]){box(side*.28,0,.69,.15,.18,.36,armor);box(side*.11,0,.28,.14,.17,.39,dark);box(side*.11,-.06,.055,.17,.29,.1,armor);box(side*.26,0,.87,.2,.24,.12,armor);}box(0,0,.46,.29,.23,.12,dark);box(.29,-.24,.6,.1,.45,.13,dark);box(.29,-.47,.6,.065,.04,.065,glow);if(has('sanvesyn'))for(let i=0;i<7;i++){box(0,.143,.5+i*.052,.09,.065,.035,glow);box(i%2?.075:-.075,.125,.5+i*.052,.065,.04,.015,dark);}if(has('plating'))box(0,-.13,.71,.33,.07,.23,['#edc18c','#aa7158','#633f48']);faces.sort((a,b)=>b.d-a.d);context.save();if(clip){const d=(x-p.x)*Math.cos(p.a)+(y-p.y)*Math.sin(p.a);context.beginPath();for(let i=0;i<480;i++)if(depth[i]>d-.4)context.rect(i*2,0,2,576);context.clip();}for(const f of faces){context.beginPath();f.pts.forEach((v,i)=>i?context.lineTo(v.x,v.y):context.moveTo(v.x,v.y));context.closePath();context.fillStyle=f.color;context.fill();context.strokeStyle='#b7e8ff35';context.lineWidth=.7;context.stroke();}context.restore();}
function drawAvatar(t){if(!paused)return;const w=avatarCanvas.width,h=avatarCanvas.height;ag.clearRect(0,0,w,h);const grad=ag.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#122840');grad.addColorStop(1,'#070f24');ag.fillStyle=grad;ag.fillRect(0,0,w,h);ag.strokeStyle='#30536b';for(let i=0;i<12;i++){ag.beginPath();ag.moveTo(0,300+i*12);ag.lineTo(w,300+i*12);ag.stroke();}ag.fillStyle='#47f9d62a';ag.beginPath();ag.ellipse(w/2,375,100,24,0,0,7);ag.fill();avatarMesh(0,0,0,avatarYaw,false,v=>{const d=3+v.y;return{x:w/2+v.x*780/d,y:225+(.58-v.z)*780/d,d};},ag);ag.fillStyle='#9bfde6';ag.font='13px monospace';ag.fillText('CHROME RUNNER / IMPLANT SCAN',18,26);ag.fillStyle='#9daec4';ag.fillText('Drag to rotate / inspect your spine',18,h-18);}
let avatarDrag=null;avatarCanvas.addEventListener('pointerdown',e=>{avatarDrag=e.clientX;avatarCanvas.setPointerCapture?.(e.pointerId);});avatarCanvas.addEventListener('pointermove',e=>{if(avatarDrag!==null){avatarYaw+=(e.clientX-avatarDrag)*.015;avatarDrag=e.clientX;}});avatarCanvas.addEventListener('pointerup',()=>avatarDrag=null);avatarCanvas.addEventListener('pointercancel',()=>avatarDrag=null);
function renderWorld(){const horizon=288+Math.tan(p.pitch||0)*738,eye=.55+(p.z||0);const sky=ctx.createLinearGradient(0,0,0,576);sky.addColorStop(0,'#171530');sky.addColorStop(.55,'#35465e');sky.addColorStop(1,'#141d35');ctx.fillStyle=sky;ctx.fillRect(0,0,960,576);ctx.fillStyle='#ffabc355';ctx.beginPath();ctx.arc(745,horizon-200,65,0,7);ctx.fill();for(let i=0;i<24;i++){let x=((i*83-p.a*140)%1100+1100)%1100-70,h=70+(i*47)%125;ctx.fillStyle=i%2?'#12233d':'#172c46';ctx.fillRect(x,horizon-h-30,65,h+40);ctx.fillStyle='#83bad66b';for(let y=horizon-h-20;y<horizon-25;y+=15)ctx.fillRect(x+10,y,35,3);}ctx.fillStyle='#202c3e';ctx.fillRect(0,Math.max(0,horizon),960,576);ctx.strokeStyle='#47708766';for(let i=-20;i<21;i++){ctx.beginPath();ctx.moveTo(480,horizon);ctx.lineTo(480+i*100,576);ctx.stroke();}for(let y=Math.max(0,horizon)+15;y<576;y+=Math.max(10,(y-horizon)*.24)){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(960,y);ctx.stroke();}
for(let i=0;i<480;i++){const a=p.a+Math.atan((i/480-.5)*1.3),d=trace(p.x,p.y,a,35),z=d*Math.cos(a-p.a);depth[i]=z;const x=p.x+Math.cos(a)*d,y=p.y+Math.sin(a)*d,height=mode==='freeplay'?2.8:2.2,top=horizon+(eye-height)*738/z,bottom=horizon+eye*738/z,h=bottom-top,side=Math.min(x%1,1-x%1)<.055,u=side?y%1:x%1,shade=Math.max(.2,1-d/36),panel=(Math.floor(x)+Math.floor(y))%3;ctx.fillStyle=`rgb(${(side?31:46)*shade},${(side?55:75)*shade},${(side?77:106)*shade})`;ctx.fillRect(i*2,top,2,h);ctx.globalAlpha=shade;ctx.fillStyle=panel===0?'#77ffdb':panel===1?'#fa8fc8':'#8baeff';ctx.fillRect(i*2,top+h*.15,2,Math.max(1,h*.009));ctx.fillRect(i*2,bottom-h*.025,2,Math.max(1,h*.01));if(u>.14&&u<.86){ctx.fillStyle='#071528';ctx.fillRect(i*2,top+h*.3,2,h*.28);ctx.fillStyle=panel===0?'#81eaff':'#ef9bcc';for(let r=0;r<3;r++)ctx.fillRect(i*2,top+h*(.33+r*.07),2,h*.012);}if(u<.025){ctx.fillStyle='#152334';ctx.fillRect(i*2,top,2,h);}ctx.globalAlpha=1;}
if(mode==='freeplay')for(const s of sites){const v=project({x:s.x,y:s.y,z:1.05});if(v&&v.x>0&&v.x<960&&v.d<depth[Math.floor(v.x/2)]+.15){const size=Math.min(50,90/v.d);ctx.save();ctx.shadowColor=s.color;ctx.shadowBlur=15;ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.strokeRect(v.x-size/2,v.y-size/2,size,size);ctx.fillStyle='#091529cc';ctx.fillRect(v.x-78,v.y-size-26,156,24);ctx.textAlign='center';text(s.name,v.x,v.y-size-9,12,s.color);ctx.textAlign='left';ctx.restore();}}
const entities=[...bots.map(b=>({kind:'bot',obj:b})),...clones.map(b=>({kind:'clone',obj:b}))].sort((a,b)=>Math.hypot(b.obj.x-p.x,b.obj.y-p.y)-Math.hypot(a.obj.x-p.x,a.obj.y-p.y));for(const e of entities)if(e.kind==='bot')drone(e.obj);else avatarMesh(e.obj.x,e.obj.y,0,e.obj.a+Math.PI/2,true,project,ctx,true);
for(const b of beams){let v1,v2;if(b.player||b.ally){v1=project(b.from);v2=project(b.to);}else{v1=project(b);v2=project({x:b.x-Math.cos(b.a)*.4,y:b.y-Math.sin(b.a)*.4,z:b.z-b.vz*.08});}if(!v1||!v2)continue;const index=Math.max(0,Math.min(479,Math.floor(v2.x/2)));if(v2.d>depth[index]+.3)continue;ctx.save();ctx.shadowColor=b.color;ctx.shadowBlur=18;ctx.strokeStyle=b.color;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(v1.x,v1.y);ctx.lineTo(v2.x,v2.y);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke();ctx.restore();}for(const s of sparks){const v=project(s);if(v&&v.x>=0&&v.x<960&&v.d<depth[Math.floor(v.x/2)]+.2){ctx.fillStyle='#c3ffff';ctx.fillRect(v.x,v.y,3,3);}}
}
draw=function(){if(!p)p={x:3.5,y:3.5,a:0,z:0,vz:0,pitch:0,hp:hpLimit()};renderWorld();const recoil=shotCD*40;ctx.save();ctx.translate(0,recoil);poly([{x:567,y:576},{x:557,y:469},{x:629,y:401},{x:701,y:445},{x:767,y:576}],'#1b263c','#718ca9');poly([{x:566,y:466},{x:629,y:401},{x:666,y:420},{x:609,y:492}],'#a1bccf','#d7eeff');poly([{x:617,y:488},{x:672,y:429},{x:741,y:576},{x:647,y:576}],'#435472','#a3b9d2');ctx.fillStyle=has('prism')?'#e19cff':'#84ffe0';ctx.fillRect(597,486,8,62);for(let i=0;i<4;i++)ctx.fillRect(654+i*9,487+i*8,6,28);text(`MK ${1+profile.mods.power}`,652,554,13);if(shotCD>.12){ctx.shadowBlur=25;ctx.shadowColor='#8affee';ctx.fillStyle='#eafff8';ctx.beginPath();ctx.arc(631,410,11,0,7);ctx.fill();}ctx.restore();if(freeze>0){ctx.fillStyle='#03ff6833';ctx.fillRect(0,0,960,576);ctx.strokeStyle='#8affa4';ctx.lineWidth=5;ctx.strokeRect(3,3,954,570);text(`TIME LOCK ${freeze.toFixed(1)}s / SPEED +85%`,285,127,19,'#baffcb');}if(hurt){ctx.fillStyle='#ff377c33';ctx.fillRect(0,0,960,576);}ctx.strokeStyle='#c6ffef';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(468,288);ctx.lineTo(476,288);ctx.moveTo(484,288);ctx.lineTo(492,288);ctx.moveTo(480,276);ctx.lineTo(480,284);ctx.moveTo(480,292);ctx.lineTo(480,300);ctx.stroke();ctx.fillStyle='#081226df';ctx.fillRect(16,16,510,76);ctx.fillRect(16,486,385,73);ctx.fillRect(775,484,168,74);text(mode==='freeplay'?'CHROME DISTRICT / FREEPLAY':`NEON BREACH / SECTOR ${sector} / WAVE ${wave}`,30,43,19,'#9deedc');text(`LV ${level()} / ${profile.credits} CR / [M] OPERATOR`,30,70,14);text(`HP ${Math.ceil(p.hp)} / ${hpLimit()}   ${reloadTime?'RELOADING':ammo+' / '+magSize()}`,30,512,18);text(`[Q] ${freezeCD>0?Math.ceil(freezeCD)+'s':'TIME LOCK'} / [C] ${cloneCD>0?Math.ceil(cloneCD)+'s':'CLONES'}`,30,540,13);text(`CARBINE MK ${profile.mods.power+1}`,789,511,14);text(`${clones.length} ALLIES`,789,538,15,'#a7bcff');
const cell=Math.min(7,145/map[0].length);for(let y=0;y<map.length;y++)for(let x=0;x<map[0].length;x++){ctx.fillStyle=map[y][x]==='1'?'#4a6c85':'#0b1528';ctx.fillRect(791+x*cell,18+y*cell,cell-1,cell-1);}if(mode==='freeplay')for(const s of sites){ctx.fillStyle=s.color;ctx.fillRect(791+s.x*cell-2,18+s.y*cell-2,5,5);}for(const b of bots){ctx.fillStyle='#ff79b0';ctx.fillRect(791+b.x*cell-1,18+b.y*cell-1,3,3);}ctx.fillStyle='#a9ffe0';ctx.fillRect(791+p.x*cell-2,18+p.y*cell-2,4,4);
if(mode==='freeplay'){const objective=mission?`${mission.site.name} / ${mission.phase==='hack'?'DOWNLOAD '+Math.floor(mission.progress/5*100)+'%':mission.phase==='fight'?'DRONES '+Math.min(4,mission.count)+'/4':'EXTRACT AT SAFEHOUSE'}`:'EXPLORE / E AT A TERMINAL TO ACCEPT A CONTRACT';ctx.fillStyle='#0a1629dd';ctx.fillRect(18,104,550,32);text(objective,30,126,13,'#ffd9a0');const close=sites.find(s=>Math.hypot(s.x-p.x,s.y-p.y)<1.5);if(close)text(`[E] ${close.name}`,365,447,17,close.color);}
if(!running){ctx.fillStyle='#081226ed';ctx.fillRect(140,208,680,151);text(started?note:'CHROME RUNNER / DISTRICT EXPANSION',168,251,21);text('FREEPLAY: contracts, upgrades, combat clones and time control.',168,288,14);text('Choose Deploy or Freeplay below. M opens your 3D operator.',168,324,14,'#a2ffe0');}if(paused){ctx.fillStyle='#02091677';ctx.fillRect(0,0,960,576);}status.textContent=note;drawAvatar(worldTime);};
document.querySelector('#start').onclick=start;document.querySelector('#freeplay').onclick=freeplay;document.querySelector('#fire').onclick=shoot;document.querySelector('#reload').onclick=reload;document.querySelector('#freeze').onclick=activate;document.querySelector('#clone').onclick=summon;document.querySelector('#jump').onclick=jump;document.querySelector('#interact').onclick=interact;document.querySelector('#menu-button').onclick=()=>toggleMenu();document.querySelector('#close-menu').onclick=()=>toggleMenu(false);document.querySelector('#loot').onclick=openLoot;document.querySelector('#menu-loot').onclick=openLoot;
// Capture overrides the original input mapping: Space now jumps, F fires.
document.addEventListener('keydown',e=>{if(['BUTTON','INPUT'].includes(e.target?.tagName)&&['Space','Enter'].includes(e.code))return;if(['Space','KeyM','KeyC','KeyE','KeyQ','KeyR','Escape'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.code==='KeyM')toggleMenu();else if(e.code==='Escape'&&paused)toggleMenu(false);else if(e.code==='Space')jump();else if(e.code==='KeyC')summon();else if(e.code==='KeyE')interact();else if(e.code==='KeyQ')activate();else if(e.code==='KeyR')reload();}else if(paused){e.stopImmediatePropagation();}else if(['ArrowUp','ArrowDown'].includes(e.code)){e.preventDefault();keys[e.code]=true;}},true);
document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&running&&!paused){p.a+=e.movementX*.0025;p.pitch=Math.max(-.65,Math.min(.65,p.pitch-e.movementY*.002));}e.stopImmediatePropagation();},true);
canvas.onclick=()=>{if(!running||paused)return;canvas.focus();try{canvas.requestPointerLock?.()?.catch?.(()=>{});}catch{}shoot();};canvas.addEventListener('pointerdown',e=>{if(e.button===0&&running&&!paused)aiming=true;});document.addEventListener('pointerup',()=>aiming=false);document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas)aiming=false;});window.addEventListener('blur',()=>{aiming=false;keys={};});persist();refresh();

