'use strict';
const c=document.querySelector('canvas'),g=c.getContext('2d'),status=document.querySelector('#status');const cards=[{name:'Sentinel',cost:3,hp:110,dmg:18,speed:34,range:23,color:'#9ad9ff'},{name:'Ranger',cost:4,hp:65,dmg:13,speed:30,range:125,color:'#a9efb4'},{name:'Colossus',cost:6,hp:300,dmg:33,speed:20,range:26,color:'#d1b5ff'},{name:'Firestorm',cost:4}];let units=[],towers=[],effects=[],energy=5,enemyEnergy=5,time=180,selected=0,running=false,ai=0,previous=0,note='Press Start to enter the arena.';
function tower(x,y,team,crown){return{x,y,team,crown,hp:crown?650:380,max:crown?650:380,range:165,dmg:22,cd:0,tower:true};}
function reset(){units=[];effects=[];towers=[tower(480,55,1,true),tower(245,130,1,false),tower(715,130,1,false),tower(480,545,0,true),tower(245,470,0,false),tower(715,470,0,false)];energy=enemyEnergy=5;time=180;ai=1;running=true;note='Match on! Deploy troops below the river.';}
function spawn(i,x,y,team){const a=cards[i];units.push({...a,x,y,team,max:a.hp,cd:0,radius:i===2?18:12});}
function select(i){selected=i;document.querySelectorAll('#actions button').forEach((b,j)=>b.style.borderColor=j===i?'#9af1cd':'#4c6383');}
cards.forEach((a,i)=>{let b=document.createElement('button');b.textContent=`${i+1} · ${a.name} · ${a.cost} energy`;b.onclick=()=>select(i);document.querySelector('#actions').append(b);});select(0);
c.addEventListener('pointerdown',e=>{if(!running)return;let r=c.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*600/r.height,a=cards[selected];if(energy<a.cost){note='Not enough energy yet.';return;}if(selected===3){for(const t of [...units,...towers])if(t.team===1&&Math.hypot(t.x-x,t.y-y)<95)t.hp-=t.tower?65:110;effects.push({x,y,r:95,life:.5});}else{if(y<340||y>570){note='Deploy on your side, below the river.';return;}spawn(selected,Math.max(35,Math.min(925,x)),y,0);}energy-=a.cost;note=`${a.name} deployed!`;});document.addEventListener('keydown',e=>{if('1234'.includes(e.key))select(+e.key-1);});document.querySelector('#reset').onclick=reset;
function end(text){running=false;note=text;}
function update(dt){time-=dt;energy=Math.min(10,energy+dt*.85);enemyEnergy=Math.min(10,enemyEnergy+dt*.85);ai-=dt;if(ai<=0){let i=Math.floor(Math.random()*3);if(enemyEnergy>=cards[i].cost){spawn(i,Math.random()<.5?245:715,175,1);enemyEnergy-=cards[i].cost;}ai=1.8;}for(const a of [...towers,...units]){if(a.hp<=0)continue;a.cd-=dt;let targets=[...units,...towers].filter(b=>b.team!==a.team&&b.hp>0).sort((b,d)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(a.x-d.x,a.y-d.y)),b=targets[0];if(!b)continue;let dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<a.range+(b.tower?22:10)){if(a.cd<=0){b.hp-=a.dmg;a.cd=a.tower?.8:1;effects.push({x:b.x,y:b.y,r:13,life:.15});}}else if(!a.tower){let tx=b.x,ty=b.y;if((a.y<300)!==(b.y<300)){tx=a.x<480?245:715;ty=Math.abs(a.x-tx)>8?(a.team?270:330):(a.team?335:265);}let d=Math.hypot(tx-a.x,ty-a.y);if(d>1){a.x+=(tx-a.x)/d*a.speed*dt;a.y+=(ty-a.y)/d*a.speed*dt;}}}units=units.filter(a=>a.hp>0);for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0);let blue=towers.find(t=>t.crown&&t.team===0),red=towers.find(t=>t.crown&&t.team===1);if(blue.hp<=0&&red.hp<=0)end('Draw! Both crowns fell.');else if(red.hp<=0)end('Victory! The enemy crown has fallen.');else if(blue.hp<=0)end('Defeat. Your crown fell — try a new strategy.');else if(time<=0){let a=towers.filter(t=>!t.team).reduce((n,t)=>n+Math.max(0,t.hp),0),b=towers.filter(t=>t.team).reduce((n,t)=>n+Math.max(0,t.hp),0);end(a>b?'Victory on remaining tower health!':a<b?'Defeat on remaining tower health.':'Draw!');}}
function draw(){g.fillStyle='#294c43';g.fillRect(0,0,960,600);for(let x=0;x<960;x+=48)for(let y=0;y<600;y+=48){g.strokeStyle='#ffffff06';g.strokeRect(x,y,48,48);}g.fillStyle='#287688';g.fillRect(0,280,960,40);for(const x of [245,715]){g.fillStyle='#c4ac7c';g.fillRect(x-43,272,86,56);g.fillStyle='#8d7659';for(let y=275;y<325;y+=10)g.fillRect(x-43,y,86,3);}g.setLineDash([6,8]);g.strokeStyle='#b9dfbe66';g.beginPath();g.moveTo(0,340);g.lineTo(960,340);g.stroke();g.setLineDash([]);for(const a of towers){g.fillStyle=a.hp<=0?'#34453f':a.team?'#e76a76':'#67baff';g.fillRect(a.x-26,a.y-24,52,48);for(let i=-1;i<=1;i++)g.fillRect(a.x+i*19-7,a.y-34,14,15);g.fillStyle='#10212b';g.font='bold 20px monospace';g.textAlign='center';g.fillText(a.crown?'♛':'♜',a.x,a.y+7);bar(a,65,42);}for(const a of units){g.fillStyle=a.team?'#f5808a':a.color;g.beginPath();g.arc(a.x,a.y,a.radius,0,7);g.fill();g.strokeStyle=a.team?'#813845':'#397296';g.lineWidth=3;g.stroke();g.fillStyle='#1b293a';g.font='bold 13px monospace';g.fillText(a.name[0],a.x,a.y+4);bar(a,32,23);}for(const e of effects){g.fillStyle=`rgba(255,192,96,${Math.min(1,e.life*2)})`;g.beginPath();g.arc(e.x,e.y,e.r,0,7);g.fill();}g.textAlign='left';g.fillStyle='#102335dc';g.fillRect(16,16,175,70);g.fillStyle='#d0f3ff';g.font='bold 19px monospace';g.fillText(`ENERGY ${energy.toFixed(1)}/10`,28,43);g.fillText(`${Math.floor(Math.max(0,time)/60)}:${String(Math.floor(Math.max(0,time)%60)).padStart(2,'0')}`,28,70);if(!running){g.fillStyle='#081120bf';g.fillRect(180,230,600,125);g.textAlign='center';g.fillStyle='white';g.font='bold 23px system-ui';g.fillText(note,480,289);g.font='16px system-ui';g.fillText('Use Start / Restart match below',480,322);}status.textContent=note;}
function bar(a,w,h){g.fillStyle='#172437';g.fillRect(a.x-w/2,a.y-h,w,5);g.fillStyle=a.team?'#ff9b9b':'#9ef0cc';g.fillRect(a.x-w/2,a.y-h,w*Math.max(0,a.hp/a.max),5);}
function frame(t){let dt=Math.min((t-previous)/1000,.05);previous=t;if(running)update(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
