'use strict';
const canvas=document.querySelector('#town'),g=canvas.getContext('2d'),W=1100,H=660;
const types=[{name:'Cindercub',element:'FIRE',color:'#ef8055',light:'#ffd084',dark:'#a54449',cost:3,hp:65,damage:13,range:4,icon:'\u{1F525}',ability:'Flame bolt'},{name:'Mossguard',element:'LEAF',color:'#63b990',light:'#b5e18c',dark:'#347b71',cost:4,hp:125,damage:15,range:1.7,icon:'\u{1F33F}',ability:'Heavy guardian'},{name:'Rainwing',element:'WATER',color:'#69bada',light:'#bbf0ee',dark:'#506dad',cost:3,hp:60,damage:9,range:5,icon:'\u{1F4A7}',ability:'Slowing stream'},{name:'Voltfox',element:'STORM',color:'#dcc573',light:'#fff0a4',dark:'#a97265',cost:5,hp:70,damage:20,range:4.5,icon:'\u26A1',ability:'Chain lightning'},{name:'Amethyst',element:'ARCANE',color:'#ba8bd6',light:'#f2c6e9',dark:'#735697',cost:5,hp:80,damage:15,range:5,icon:'\u2726',ability:'Healing aura'}];
const fresh=()=>({owned:[0],collected:[],wins:0,champion:false});let saveData=fresh();try{const s=JSON.parse(localStorage.getItem('cardbound-town-v1'));if(s&&Array.isArray(s.owned)&&Array.isArray(s.collected)){saveData={...fresh(),...s};saveData.owned=saveData.owned.filter(i=>Number.isInteger(i)&&i>=0&&i<5);if(!saveData.owned.includes(0))saveData.owned.unshift(0);}}catch{}
const houses=[{x:-7,z:-6,w:4,d:3,h:2.6,roof:'#bc665d',color:'#f5dfbd'},{x:6,z:-7,w:3.8,d:3.5,h:3,roof:'#658eaa',color:'#f0e2c8'},{x:-8,z:5,w:4,d:3.2,h:2.7,roof:'#869565',color:'#e4d5b5'},{x:7,z:5,w:3.6,d:3.5,h:2.6,roof:'#a579a4',color:'#f0ded4'},{x:0,z:-12,w:4,d:2.5,h:3.1,roof:'#6a908b',color:'#f1e1b4'}];
const trees=[[-12,-11],[-11,-2],[-13,4],[-11,10],[-6,12],[5,12],[11,10],[12,3],[11,-3],[12,-11],[-4,-11],[5,-13]];
const pickups=[{id:1,x:-5,z:2},{id:2,x:5,z:-3},{id:3,x:-9,z:-10},{id:4,x:10,z:9}];
let player={x:0,z:6,y:0,vy:0,hp:100,a:0},allies=[],enemies=[],effects=[],mana=10,selected=0,keys={},time=0,last=0,active=false,arena=false,pulseCD=0,summonCD=0,toast='Welcome to Willowmere. Your first creature card is ready.',camYaw=0,camPitch=.62,camDistance=10,drag=null,faces=[];
const clinic={x:-3,z:5},shrine={x:0,z:-8};let camera;
function persist(){try{localStorage.setItem('cardbound-town-v1',JSON.stringify(saveData));}catch{}}
function say(t){toast=t;document.querySelector('#town-toast').textContent=t;}
function hud(){document.querySelector('#town-health').textContent=`${Math.ceil(player.hp)} / 100`;document.querySelector('#hp-meter').style.width=player.hp+'%';document.querySelector('#mana-label').textContent=`${mana.toFixed(1)} / 10`;document.querySelector('#mana-meter').style.width=mana*10+'%';document.querySelector('#quest').textContent=saveData.champion?'Crown Guardian defeated!':arena?'Defeat the Crown Guardian':saveData.owned.length>=3?'Visit the gold guardian beacon':`Collect three creature types (${saveData.owned.length}/3)`;document.querySelector('#collection').textContent=`${saveData.owned.length} / 5 CARDS / ${saveData.wins} WINS`;}
function deck(){const parent=document.querySelector('#deck');parent.replaceChildren();types.forEach((t,i)=>{const b=document.createElement('button'),owned=saveData.owned.includes(i);b.className=`summon-card ${selected===i?'selected':''} ${owned?'':'locked'}`;b.innerHTML=`<span class="cost">${t.cost}</span><span class="card-art" aria-hidden="true">${t.icon}</span><strong>${i+1}. ${t.name}</strong><small>${t.element} / ${owned?t.ability:'FIND IN TOWN'}</small>`;b.onclick=()=>{if(!owned){say('Find this glowing card in town to unlock it.');return;}selected=i;deck();say(`${t.name} selected. Press Q or Summon to call it.`);};parent.append(b);});hud();}
function blocked(x,z,r=.3){return Math.abs(x)>14||Math.abs(z)>14||houses.some(h=>Math.abs(x-h.x)<h.w/2+r&&Math.abs(z-h.z)<h.d/2+r)||trees.some(([tx,tz])=>Math.hypot(tx-x,tz-z)<.5+r);}
function move(o,dx,dz){if(!blocked(o.x+dx,o.z))o.x+=dx;if(!blocked(o.x,o.z+dz))o.z+=dz;}
function visible(a,b){const d=Math.hypot(a.x-b.x,a.z-b.z);for(let s=.3;s<d;s+=.3){if(blocked(a.x+(b.x-a.x)*s/d,a.z+(b.z-a.z)*s/d,.08))return false;}return true;}
function resetEnemies(){enemies=[{x:-5,z:-3,type:2},{x:5,z:1,type:0},{x:2,z:-10,type:3}].map((e,i)=>({...e,hp:45,max:45,cd:1+i,slow:0,boss:false}));}
function summon(){if(!active)return;const t=types[selected];if(mana<t.cost){say('Your summon energy is recharging.');return;}if(summonCD>0)return;if(allies.length>=4){say('Your party is full. Up to four companions can fight at once.');return;}let x=player.x+Math.sin(player.a)*1.1,z=player.z-Math.cos(player.a)*1.1;if(blocked(x,z)){x=player.x;z=player.z;}mana-=t.cost;summonCD=.6;allies.push({x,z,y:0,a:0,type:selected,hp:t.hp,max:t.hp,cd:.4});effects.push({kind:'ring',x,z,y:.1,life:.7,max:.7,color:t.light});say(`${t.name} summoned! It will fight nearby enemies and follow you.`);}
function damage(e,n){e.hp-=n;if(e.hp<=0){enemies=enemies.filter(x=>x!==e);saveData.wins++;mana=Math.min(10,mana+2);if(e.boss){arena=false;saveData.champion=true;say('CROWN BADGE EARNED! You are Willowmere\'s champion.');}else say('Battle won! +2 summon energy.');persist();}}
function pulse(){if(!active||pulseCD>0)return;pulseCD=1.2;effects.push({kind:'ring',x:player.x,z:player.z,y:.3,life:.5,max:.5,color:'#fff3b9'});let hits=0;for(const e of [...enemies])if(Math.hypot(e.x-player.x,e.z-player.z)<4&&visible(player,e)){damage(e,8);hits++;}if(!hits)say('Magic pulse! Move within four steps of an enemy.');}
function interact(){if(!active)return;if(Math.hypot(player.x-clinic.x,player.z-clinic.z)<2){player.hp=100;mana=10;for(const a of allies)a.hp=a.max;say('The Willow Well restored your health, party, and summon energy.');return;}if(Math.hypot(player.x-shrine.x,player.z-shrine.z)<2){if(arena){say('The Crown Guardian is already on the field!');return;}if(saveData.owned.length<3){say('Collect three creature types to unlock the guardian challenge.');return;}arena=true;enemies.push({x:0,z:-5,type:4,hp:210,max:210,cd:1,slow:0,boss:true});say('Crown Guardian summoned. Use your creature cards and magic pulse!');return;}say('Find a glowing card, the green healing well, or the gold guardian beacon.');}
function jump(){if(active&&player.y===0)player.vy=4;}
function update(dt){if(!active)return;time+=dt;mana=Math.min(10,mana+dt*.65);pulseCD=Math.max(0,pulseCD-dt);summonCD=Math.max(0,summonCD-dt);const forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),side=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),speed=dt*(keys.ShiftLeft?4.5:3.2)/Math.max(1,Math.hypot(forward,side));const dx=(Math.sin(camYaw)*forward+Math.cos(camYaw)*side)*speed,dz=(-Math.cos(camYaw)*forward+Math.sin(camYaw)*side)*speed;move(player,dx,dz);if(dx||dz)player.a=Math.atan2(dx,-dz);player.vy-=dt*10;player.y=Math.max(0,player.y+player.vy*dt);if(!player.y)player.vy=0;
for(const item of pickups)if(!saveData.collected.includes(item.id)&&Math.hypot(player.x-item.x,player.z-item.z)<1.2){saveData.collected.push(item.id);if(!saveData.owned.includes(item.id))saveData.owned.push(item.id);selected=item.id;persist();deck();effects.push({kind:'ring',x:item.x,z:item.z,y:.5,life:1,max:1,color:types[item.id].light});say(`NEW CARD / ${types[item.id].name}! Press Q to summon it.`);}
for(const a of allies){a.cd-=dt;const t=types[a.type],enemy=[...enemies].filter(e=>Math.hypot(e.x-a.x,e.z-a.z)<7&&visible(a,e)).sort((b,c)=>Math.hypot(b.x-a.x,b.z-a.z)-Math.hypot(c.x-a.x,c.z-a.z))[0];if(enemy){const d=Math.hypot(enemy.x-a.x,enemy.z-a.z);a.a=Math.atan2(enemy.x-a.x,-(enemy.z-a.z));if(d>t.range)move(a,(enemy.x-a.x)/d*dt*2.6,(enemy.z-a.z)/d*dt*2.6);else if(a.cd<=0){effects.push({kind:'bolt',from:{x:a.x,y:.65,z:a.z},to:{x:enemy.x,y:.65,z:enemy.z},life:.3,max:.3,color:t.light});if(a.type===2)enemy.slow=2;if(a.type===3){const second=enemies.find(e=>e!==enemy&&Math.hypot(e.x-enemy.x,e.z-enemy.z)<3);if(second){effects.push({kind:'bolt',from:{x:enemy.x,y:.65,z:enemy.z},to:{x:second.x,y:.65,z:second.z},life:.3,max:.3,color:t.light});damage(second,8);}}damage(enemy,t.damage);a.cd=a.type===1?1.1:.85;}}else{const d=Math.hypot(player.x-a.x,player.z-a.z);if(d>2)move(a,(player.x-a.x)/d*dt*3,(player.z-a.z)/d*dt*3);}if(a.type===4){player.hp=Math.min(100,player.hp+dt*1.5);for(const other of allies)other.hp=Math.min(other.max,other.hp+dt);}}
for(const e of enemies){e.cd-=dt;e.slow=Math.max(0,e.slow-dt);const target=[player,...allies].sort((a,b)=>Math.hypot(a.x-e.x,a.z-e.z)-Math.hypot(b.x-e.x,b.z-e.z))[0],d=Math.hypot(e.x-target.x,e.z-target.z);if(d>8&&!e.boss)continue;if(!visible(e,target))continue;if(d>1.5)move(e,(target.x-e.x)/d*dt*(e.slow?.5:1.35),(target.z-e.z)/d*dt*(e.slow?.5:1.35));else if(e.cd<=0){target.hp-=e.boss?18:8;e.cd=1.2;effects.push({kind:'ring',x:target.x,z:target.z,y:.4,life:.3,max:.3,color:'#ff9b91'});}}
allies=allies.filter(a=>a.hp>0);effects.forEach(e=>e.life-=dt);effects=effects.filter(e=>e.life>0);if(player.hp<=0){player={x:0,z:6,y:0,vy:0,hp:100,a:0};allies=[];arena=false;mana=10;resetEnemies();say('The Willow Well revived you. Your collected cards are safe.');}hud();}
function cameraPoint(v){const dx=v.x-camera.x,dy=v.y-camera.y,dz=v.z-camera.z;return{x:dx*camera.rx+dz*camera.rz,y:dx*camera.ux+dy*camera.uy+dz*camera.uz,z:dx*camera.fx+dy*camera.fy+dz*camera.fz};}
function screen(v){const q=cameraPoint(v);return q.z>.12?{x:W/2+q.x*720/q.z,y:H/2-q.y*720/q.z,d:q.z}:null;}
function face(vertices,color){let points=vertices.map(cameraPoint),clipped=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],inside=a.z>.15,next=b.z>.15;if(inside)clipped.push(a);if(inside!==next){const t=(.15-a.z)/(b.z-a.z);clipped.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:.15});}}if(clipped.length<3)return;faces.push({points:clipped.map(v=>({x:W/2+v.x*720/v.z,y:H/2-v.y*720/v.z})),depth:clipped.reduce((n,v)=>n+v.z,0)/clipped.length,color});}
function box(x,y,z,w,h,d,colors,yaw=0){const v=[];for(const yy of [-1,1])for(const zz of [-1,1])for(const xx of [-1,1]){const lx=xx*w/2,lz=zz*d/2;v.push({x:x+lx*Math.cos(yaw)-lz*Math.sin(yaw),y:y+yy*h/2,z:z+lx*Math.sin(yaw)+lz*Math.cos(yaw)});}const col=Array.isArray(colors)?colors:[colors,colors,colors];for(const [idx,i] of [[[0,1,3,2],2],[[4,6,7,5],0],[[0,4,5,1],1],[[2,3,7,6],2],[[0,2,6,4],1],[[1,5,7,3],2]])face(idx.map(n=>v[n]),col[i]);}
function pyramid(x,y,z,w,h,d,colors){const base=[{x:x-w/2,y,z:z-d/2},{x:x+w/2,y,z:z-d/2},{x:x+w/2,y,z:z+d/2},{x:x-w/2,y,z:z+d/2}],top={x,y:y+h,z};for(let i=0;i<4;i++)face([base[i],base[(i+1)%4],top],colors[i%colors.length]);}
function creature(a,enemy=false){const t=types[a.type],s=a.boss?1.7:1,bob=Math.sin(time*3+a.x)*.045;let x=a.x,z=a.z,y=.5*s+bob;box(x,y,z,.62*s,.63*s,.55*s,[t.light,t.color,t.dark]);box(x-.2*s,y+.43*s,z,.17*s,.33*s,.18*s,[t.light,t.color,t.dark]);box(x+.2*s,y+.43*s,z,.17*s,.33*s,.18*s,[t.light,t.color,t.dark]);for(const side of [-1,1]){box(x+side*.19*s,.12*s,z-.09*s,.25*s,.17*s,.32*s,[t.light,t.color,t.dark]);box(x+side*.14*s,y+.07*s,z+.29*s,.115*s,.14*s,.035*s,['#fff9e9','#fff9e9','#fff9e9']);box(x+side*.13*s,y+.065*s,z+.315*s,.052*s,.09*s,.025*s,['#243945','#243945','#243945']);}box(x,y-.09*s,z+.3*s,.12*s,.04*s,.025*s,t.dark);if(a.type===2){pyramid(x-.5*s,y-.1*s,z,.4*s,.45*s,.22*s,[t.light,t.color]);pyramid(x+.5*s,y-.1*s,z,.4*s,.45*s,.22*s,[t.light,t.color]);}if(a.type===1)pyramid(x,y+.3*s,z,.4*s,.6*s,.4*s,['#a1db7c','#51a780']);if(a.type===3)pyramid(x,y+.3*s,z,.24*s,.6*s,.18*s,['#fff2b0','#f2c459']);if(a.boss){box(x,y+.8*s,z,.65*s,.12*s,.4*s,['#fff1af','#ecc66e','#be934d']);for(let i=-1;i<=1;i++)box(x+i*.24*s,y+.94*s,z,.1*s,.22*s,.25*s,'#fbe2a0');}}
function playerMesh(){const x=player.x,z=player.z,y=player.y;box(x,y+.75,z,.43,.58,.27,['#c1eee2','#5dabb2','#396e8d'],player.a);box(x,y+1.19,z,.33,.34,.3,['#ffe5b7','#e6bc97','#ba917b'],player.a);box(x,y+1.38,z,.38,.12,.35,['#efd589','#d3a965','#a78256'],player.a);for(const side of [-1,1]){box(x+side*.13,y+.27,z,.16,.42,.18,['#68758e','#46566f','#303d59']);box(x+side*.31,y+.73,z,.14,.43,.17,['#d1ecce','#72a2a9','#437285']);}box(x,y+.76,z+.2,.34,.35,.16,['#c9a575','#a67f5f','#805e51']);}
function draw(){camera={x:player.x-Math.sin(camYaw)*Math.cos(camPitch)*camDistance,y:1+Math.sin(camPitch)*camDistance,z:player.z+Math.cos(camYaw)*Math.cos(camPitch)*camDistance,rx:Math.cos(camYaw),rz:Math.sin(camYaw),ux:Math.sin(camYaw)*Math.sin(camPitch),uy:Math.cos(camPitch),uz:-Math.cos(camYaw)*Math.sin(camPitch),fx:Math.sin(camYaw)*Math.cos(camPitch),fy:-Math.sin(camPitch),fz:-Math.cos(camYaw)*Math.cos(camPitch)};const sky=g.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#8fb6c9');sky.addColorStop(.6,'#d9e7d1');sky.addColorStop(1,'#a2bea0');g.fillStyle=sky;g.fillRect(0,0,W,H);g.fillStyle='#fef0c7';g.beginPath();g.arc(880,100,49,0,7);g.fill();faces=[];
for(let x=-16;x<16;x+=2)for(let z=-16;z<16;z+=2){const path=Math.abs(x)<2||Math.abs(z-2)<2;face([{x,y:-.04,z},{x:x+2,y:-.04,z},{x:x+2,y:-.04,z:z+2},{x,y:-.04,z:z+2}],path?((x+z)%4?'#d7c8a6':'#e2d2b1'):((x+z)%4?'#8fac7e':'#98b688'));}
for(const h of houses){box(h.x,h.h/2,h.z,h.w,h.h,h.d,['#fff2d2',h.color,'#c2b99e']);pyramid(h.x,h.h,h.z,h.w+.5,1.4,h.d+.5,[h.roof,h.roof,'#775e65','#ad8a79']);box(h.x,.7,h.z+h.d/2+.04,.8,1.4,.09,['#725f55','#826957','#69584b']);for(const side of [-1,1]){box(h.x+side*h.w*.3,1.6,h.z+h.d/2+.06,.65,.7,.07,['#fdf6c5','#a0cbd0','#a0cbd0']);box(h.x+side*h.w*.3,1.6,h.z+h.d/2+.11,.055,.7,.02,'#f2e2b8');}box(h.x+h.w*.25,h.h+.6,h.z-.5,.45,1.1,.45,['#d7b79d','#bc9383','#997b76']);}
for(const [x,z] of trees){box(x,.7,z,.35,1.4,.35,['#af8e64','#92734f','#735e49']);pyramid(x,.8,z,2.3,2.4,2.3,['#9ec992','#6fa781','#548577']);pyramid(x,1.7,z,1.8,1.9,1.8,['#b1d295','#79ae84','#618d78']);}
box(clinic.x,.25,clinic.z,1.4,.5,1.4,['#cbd9c0','#94aa9e','#7e9795']);box(clinic.x,.5,clinic.z,1,.08,1,['#8cf0d2','#74cfcb','#70bfc1']);pyramid(clinic.x,1+Math.sin(time*2)*.12,clinic.z,.3,.6,.3,['#c3ffb5','#80dbab']);box(shrine.x,.16,shrine.z,2,.3,2,['#dfd8b6','#b5ad94','#939a90']);pyramid(shrine.x,1+Math.sin(time*2)*.12,shrine.z,.45,.7,.45,['#fff0b0','#e5ba6e']);
for(const item of pickups)if(!saveData.collected.includes(item.id)){const t=types[item.id];box(item.x,.9+Math.sin(time*2+item.id)*.14,item.z,.6,.85,.09,[t.light,t.color,t.dark],time*.6);pyramid(item.x,1.45,item.z,.2,.3,.2,[t.light,t.color]);}
for(const a of allies)creature(a);for(const e of enemies)creature(e,true);playerMesh();for(const e of effects)if(e.kind==='ring'){const r=(1-e.life/e.max)*2;for(let i=0;i<16;i++){const a=i*Math.PI/8;box(e.x+Math.cos(a)*r,e.y,e.z+Math.sin(a)*r,.08,.15,.08,e.color);}}
faces.sort((a,b)=>b.depth-a.depth);for(const f of faces){g.beginPath();f.points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath();g.fillStyle=f.color;g.fill();g.strokeStyle=f.color;g.lineWidth=.5;g.stroke();}
for(const e of effects)if(e.kind==='bolt'){const a=screen(e.from),b=screen(e.to);if(a&&b){g.save();g.strokeStyle=e.color;g.lineWidth=4;g.shadowColor=e.color;g.shadowBlur=14;g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke();g.restore();}}
for(const e of [...enemies,...allies]){const v=screen({x:e.x,y:e.boss?2.8:1.65,z:e.z});if(v&&visible(player,e)){g.fillStyle='#1d3e45cc';g.fillRect(v.x-23,v.y,46,5);g.fillStyle=enemies.includes(e)?'#f29189':'#adf0c4';g.fillRect(v.x-23,v.y,46*Math.max(0,e.hp/e.max),5);}}
g.fillStyle='#163b40d9';g.fillRect(W-130,H-176,112,112);for(const h of houses){g.fillStyle='#bfd2b9';g.fillRect(W-74+h.x*3-h.w*1.5,H-120+h.z*3-h.d*1.5,h.w*3,h.d*3);}for(const item of pickups)if(!saveData.collected.includes(item.id)){g.fillStyle=types[item.id].light;g.fillRect(W-76+item.x*3,H-122+item.z*3,4,4);}g.fillStyle='#ffe19b';g.fillRect(W-76+shrine.x*3,H-122+shrine.z*3,4,4);g.fillStyle='#a2ffd3';g.fillRect(W-76+clinic.x*3,H-122+clinic.z*3,4,4);g.fillStyle='white';g.beginPath();g.arc(W-74+player.x*3,H-120+player.z*3,3,0,7);g.fill();
document.querySelector('#town-tip').textContent=Math.hypot(player.x-clinic.x,player.z-clinic.z)<2?'E / Heal your party':Math.hypot(player.x-shrine.x,player.z-shrine.z)<2?'E / Challenge the Crown Guardian':`${allies.length}/4 companions / Q summons ${types[selected].name}`;}
document.querySelector('#begin-town').onclick=()=>{active=true;document.querySelector('#town-start').hidden=true;canvas.focus();};document.querySelector('#summon').onclick=summon;document.querySelector('#pulse').onclick=pulse;document.querySelector('#town-interact').onclick=interact;document.querySelector('#town-jump').onclick=jump;document.querySelector('#town-reset').onclick=()=>{if(confirm('Reset your Cardbound collection and victories?')){try{localStorage.removeItem('cardbound-town-v1');}catch{}location.reload();}};
document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&e.target.tagName!=='BUTTON')e.preventDefault();if(e.target.tagName==='BUTTON'&&['Space','Enter'].includes(e.code))return;keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyQ')summon();if(e.code==='KeyF')pulse();if(e.code==='KeyE')interact();if(e.code==='Space')jump();if(/^Digit[1-5]$/.test(e.code)){const id=Number(e.code.slice(-1))-1;if(saveData.owned.includes(id)){selected=id;deck();}}});document.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>keys={});
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);canvas.focus();});canvas.addEventListener('pointermove',e=>{if(!drag)return;camYaw-=(e.clientX-drag.x)*.008;camPitch=Math.max(.32,Math.min(1.05,camPitch+(e.clientY-drag.y)*.006));drag={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();camDistance=Math.max(6,Math.min(15,camDistance+e.deltaY*.01));},{passive:false});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{keys[b.dataset.key]=true;b.setPointerCapture?.(e.pointerId);});b.addEventListener('pointerup',()=>keys[b.dataset.key]=false);b.addEventListener('pointercancel',()=>keys[b.dataset.key]=false);});resetEnemies();deck();function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
