'use strict';
saveData.captured=Array.isArray(saveData.captured)?saveData.captured:[];
saveData.defeated=Array.isArray(saveData.defeated)?saveData.defeated:[];
const trainers=[{id:'mira',name:'Mira / Garden Scout',x:-4,z:7,team:[1,2],color:'#8acb9d'},{id:'jax',name:'Jax / Storm Courier',x:4,z:-3,team:[0,3],color:'#efc779'},{id:'nova',name:'Nova / Arcane Keeper',x:9,z:0,team:[4,1,3],color:'#cfa2de'}];
let duel=null;
const normalDamage=damage,normalInteract=interact,normalUpdate=update,normalDraw=draw,normalPlayerMesh=playerMesh,normalHud=hud;
function captureMonster(){if(!active)return;const target=[...enemies].filter(e=>!e.boss&&!e.trainer&&Math.hypot(e.x-player.x,e.z-player.z)<4&&visible(player,e)).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0];if(!target){say('Find a wild creature within four steps. Trainer monsters cannot be captured.');return;}if(target.hp>target.max*.5){say(`Weaken ${types[target.type].name} below half health, then press R to capture it.`);return;}enemies=enemies.filter(e=>e!==target);saveData.captured.push(target.type);if(!saveData.owned.includes(target.type))saveData.owned.push(target.type);selected=target.type;mana=Math.min(10,mana+2);effects.push({kind:'ring',x:target.x,z:target.z,y:.7,life:1,max:1,color:types[target.type].light});persist();deck();say(`CAPTURED / ${types[target.type].name}! Its summoning card is permanently yours.`);}
function trainerNear(){return trainers.find(t=>Math.hypot(t.x-player.x,t.z-player.z)<2);}
interact=function(){const trainer=trainerNear();if(!trainer){normalInteract();return;}if(!active)return;if(duel||arena){say('Finish your current challenge before starting a trainer battle.');return;}duel=trainer;const spots=[];for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)if(!blocked(trainer.x+dx,trainer.z+dz)&&Math.hypot(dx,dz)>1)spots.push({x:trainer.x+dx,z:trainer.z+dz});trainer.team.forEach((type,i)=>{const pos=spots[i]||{x:trainer.x,z:trainer.z};enemies.push({...pos,type,hp:65+i*12,max:65+i*12,cd:1.5,slow:0,boss:false,trainer:trainer.id});});say(`${trainer.name}: Let's battle! Defeat my ${trainer.team.length} creatures.`);};
damage=function(enemy,amount){normalDamage(enemy,amount);if(duel&&!enemies.some(e=>e.trainer===duel.id)){const rival=duel;duel=null;if(!saveData.defeated.includes(rival.id)){saveData.defeated.push(rival.id);const reward=rival.team[rival.team.length-1];if(!saveData.owned.includes(reward))saveData.owned.push(reward);say(`RIVAL DEFEATED / ${rival.name}. Earned the ${types[reward].name} card!`);}else say(`REMATCH WON / ${rival.name}. Party healed and energy restored!`);mana=10;player.hp=100;for(const a of allies)a.hp=a.max;persist();deck();}};
update=function(dt){normalUpdate(dt);if(duel&&!enemies.some(e=>e.trainer===duel.id)){duel=null;say('You were revived at the well. Train your party and challenge the rival again.');}};
hud=function(){normalHud();document.querySelector('#collection').textContent=`${saveData.owned.length}/5 CARDS / ${saveData.captured.length} CAPTURES / ${saveData.defeated.length}/3 RIVALS`;if(duel)document.querySelector('#quest').textContent=`Rival battle: ${duel.name.split(' / ')[0]}`;};
playerMesh=function(){normalPlayerMesh();for(const t of trainers){box(t.x,.76,t.z,.44,.56,.28,[t.color,t.color,'#506985']);box(t.x,1.19,t.z,.33,.33,.29,['#ffe4b6','#e3ba97','#b58f7b']);box(t.x,1.38,t.z,.4,.13,.35,['#ebdca7',t.color,'#667586']);for(const side of [-1,1]){box(t.x+side*.13,.27,t.z,.16,.42,.19,['#6b7d95','#465d74','#314257']);box(t.x+side*.32,.76,t.z,.14,.43,.18,[t.color,t.color,'#657a83']);}box(t.x+.39,.69,t.z+.04,.17,.25,.06,['#fff2b5','#d7bb88','#9d8b66']);}};
draw=function(){normalDraw();for(const t of trainers){const s=screen({x:t.x,y:1.85,z:t.z});if(s&&visible(player,t)&&Math.hypot(player.x-t.x,player.z-t.z)<12){g.font='bold 12px system-ui';g.textAlign='center';g.fillStyle='#183841d9';g.fillRect(s.x-81,s.y-18,162,24);g.fillStyle=saveData.defeated.includes(t.id)?'#c4efad':'#fff3c8';g.fillText(`${saveData.defeated.includes(t.id)?'★ ':''}${t.name.split(' / ')[0]} / RIVAL`,s.x,s.y-2);g.textAlign='left';}}const rival=trainerNear();if(rival)document.querySelector('#town-tip').textContent=`E / Challenge ${rival.name.split(' / ')[0]}`;};
document.querySelector('#town-interact').onclick=interact;
document.querySelector('#capture').onclick=captureMonster;
document.addEventListener('keydown',e=>{if(e.code==='KeyR'&&!e.repeat)captureMonster();});
deck();persist();
